### ISSUE TITLE
Getting LOW_CACHE when migrate from Ubuntu 18.05

### ISSUE THREAD

**Issue by AhmadIbrahiim** [imfunniee/htmlOS#1]
Hello,

I'm getting this error  `LOW_CACHE` when I use the migration wizard to migrate from Ubuntu 18.05!!

Any information about this?

**Comment by imfunniee** [comment]
Hey,

It's prob cause we are using jquery, we gonna move to a more efficient [thanosjs](https://thanosjs.org) to reduce the memory by 50%.

Hope it fixes the error. Until then you can try this [fix](https://askubuntu.com/questions/41778/computer-freezing-on-almost-full-ram-possibly-disk-cache-problem).

funny

**Comment by angelotrabuco** [comment]
April Fools! :)
